# Generated by Django 3.1.3 on 2020-12-10 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_app_open',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
    ]
