# Generated by Django 3.1.3 on 2020-12-10 08:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_auto_20201210_0817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feeling',
            name='rate',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)]),
        ),
    ]
