# Generated by Django 3.1.3 on 2020-12-11 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_auto_20201210_0817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dream',
            name='dream_clearance',
            field=models.PositiveSmallIntegerField(choices=[(1, 'cloudy'), (2, 'normal'), (3, 'clear'), (4, 'super_clear')], default=2, max_length=16),
        ),
    ]
