# Generated by Django 3.1.3 on 2020-12-11 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0010_auto_20201211_0708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dream',
            name='dream_clearance',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Cloudy'), (2, 'Normal'), (3, 'Clear'), (4, 'Super clear')], default=2),
        ),
    ]
