# Generated by Django 3.1.3 on 2020-12-11 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0011_auto_20201211_0837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dream',
            name='dream_clearance',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Cloudy'), (1, 'Normal'), (2, 'Clear'), (3, 'Super clear')], default=1),
        ),
    ]
