# Generated by Django 3.1.3 on 2020-12-17 12:27

from django.db import migrations
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0012_auto_20201211_0837'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_type',
            field=model_utils.fields.StatusField(choices=[(0, 'dummy')], default='timeline', max_length=100, no_check_for_status=True),
        ),
    ]
