# Generated by Django 3.1.4 on 2021-01-14 10:10

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DreamerConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('version', model_utils.fields.StatusField(choices=[('v1', 'v1'), ('v2', 'v2'), ('v3', 'v3')], default='v1', max_length=100, no_check_for_status=True)),
                ('main_background', models.ImageField(upload_to='configurations/')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
