# Generated by Django 3.1.3 on 2020-12-04 09:06

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields
import utils.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DreamerConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('main_background', models.ImageField(upload_to='configurations/')),
            ],
            options={
                'abstract': False,
            },
            bases=(utils.models.ModelVersionMixin, models.Model),
        ),
    ]
