# Generated by Django 3.1.3 on 2020-12-04 09:12

from django.db import migrations
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dreamerconfiguration',
            name='version',
            field=model_utils.fields.StatusField(choices=[(0, 'dummy')], default='v1', max_length=100, no_check_for_status=True),
        ),
    ]
