# Generated by Django 3.1.3 on 2020-12-10 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0003_feelingdetail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FeelingDetail',
        ),
    ]
